# Generated by Django 4.1 on 2022-08-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasesData', '0006_alter_product_options_product_my_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
