# Generated by Django 4.1 on 2022-08-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasesData', '0007_alter_purchase_options_purchase_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='store',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
