# Generated by Django 3.2.9 on 2022-07-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_data', '0004_remove_purchase_products_alter_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='purchase',
            name='non_cash_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='FIN',
            field=models.CharField(default='FIN_UNKNOWN', max_length=7),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='purchases_data.Category'),
        ),
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
        migrations.AddField(
            model_name='purchaseunit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases_data.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='all_purchses',
            field=models.ManyToManyField(to='purchases_data.PurchaseUnit'),
        ),
    ]
