# Generated by Django 3.2.9 on 2022-07-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_data', '0005_auto_20220729_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIN', models.CharField(default='FIN_UNKNOWN', max_length=7, verbose_name='Fin')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='FIN',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchases_data.person'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
