# Generated by Django 3.2.9 on 2022-07-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_data', '0009_rename_name_testclass_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
